### PR TITLE
Web client add testing

### PR DESCRIPTION
**Pull request by gumbyscout**

### CODE REVIEW

**Comment by nictuku** [comment]
How do we run these tests as part of deploy.sh?

**Comment by gumbyscout** [comment]
```
npm test
```
is the command you'd run for a deploy

**Comment by nictuku** [comment]
I tried to use npm test after doing "npm install", but I still got this:

https://gist.github.com/nictuku/66529769b9a09fdafd8161079467288f

Then it freezes, like waiting for me to go to that URL to test stuff. But this is supposed to be headless, right?

Are there other commands missing?

**Comment by gumbyscout** [comment]
Sorry, I forgot that it runs endlessly by default try
```
$ karma start --single-run
```
That should just run the test runner once, even if it errors out.

**Comment by nictuku** [comment]
I guess I need "npm install karma" first, right?

**Comment by nictuku** [comment]
I'm getting missing dependencies again.

https://gist.github.com/nictuku/e9db95802de6f0386f0c6b95b753895c

I'm doing "npm install webpack nyan" now, let's see.

**Comment by nictuku** [comment]
I'm surprised I apparently need alsa :-P

https://gist.github.com/nictuku/fc107997e07a9a99112b1ee2db611ea6

**Comment by nictuku** [comment]
I'm going to go ahead and merge this blindly without running the integration tests. I'm too tired to figure this out now.

**Pull request merged**
